[build]
  command = "npm run build"
  publish = ".output/public"
  
[build.environment]
  # Next.js specific settings
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/_nuxt/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  framework = "nextjs"
